require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaymentNotifiesController do

  # This should return the minimal set of attributes required to create a valid
  # PaymentNotify. As you add validations to PaymentNotify, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "payment" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaymentNotifiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all payment_notifies as @payment_notifies" do
      payment_notify = PaymentNotify.create! valid_attributes
      get :index, {}, valid_session
      assigns(:payment_notifies).should eq([payment_notify])
    end
  end

  describe "GET show" do
    it "assigns the requested payment_notify as @payment_notify" do
      payment_notify = PaymentNotify.create! valid_attributes
      get :show, {:id => payment_notify.to_param}, valid_session
      assigns(:payment_notify).should eq(payment_notify)
    end
  end

  describe "GET new" do
    it "assigns a new payment_notify as @payment_notify" do
      get :new, {}, valid_session
      assigns(:payment_notify).should be_a_new(PaymentNotify)
    end
  end

  describe "GET edit" do
    it "assigns the requested payment_notify as @payment_notify" do
      payment_notify = PaymentNotify.create! valid_attributes
      get :edit, {:id => payment_notify.to_param}, valid_session
      assigns(:payment_notify).should eq(payment_notify)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaymentNotify" do
        expect {
          post :create, {:payment_notify => valid_attributes}, valid_session
        }.to change(PaymentNotify, :count).by(1)
      end

      it "assigns a newly created payment_notify as @payment_notify" do
        post :create, {:payment_notify => valid_attributes}, valid_session
        assigns(:payment_notify).should be_a(PaymentNotify)
        assigns(:payment_notify).should be_persisted
      end

      it "redirects to the created payment_notify" do
        post :create, {:payment_notify => valid_attributes}, valid_session
        response.should redirect_to(PaymentNotify.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payment_notify as @payment_notify" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotify.any_instance.stub(:save).and_return(false)
        post :create, {:payment_notify => { "payment" => "invalid value" }}, valid_session
        assigns(:payment_notify).should be_a_new(PaymentNotify)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotify.any_instance.stub(:save).and_return(false)
        post :create, {:payment_notify => { "payment" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payment_notify" do
        payment_notify = PaymentNotify.create! valid_attributes
        # Assuming there are no other payment_notifies in the database, this
        # specifies that the PaymentNotify created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaymentNotify.any_instance.should_receive(:update).with({ "payment" => "" })
        put :update, {:id => payment_notify.to_param, :payment_notify => { "payment" => "" }}, valid_session
      end

      it "assigns the requested payment_notify as @payment_notify" do
        payment_notify = PaymentNotify.create! valid_attributes
        put :update, {:id => payment_notify.to_param, :payment_notify => valid_attributes}, valid_session
        assigns(:payment_notify).should eq(payment_notify)
      end

      it "redirects to the payment_notify" do
        payment_notify = PaymentNotify.create! valid_attributes
        put :update, {:id => payment_notify.to_param, :payment_notify => valid_attributes}, valid_session
        response.should redirect_to(payment_notify)
      end
    end

    describe "with invalid params" do
      it "assigns the payment_notify as @payment_notify" do
        payment_notify = PaymentNotify.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotify.any_instance.stub(:save).and_return(false)
        put :update, {:id => payment_notify.to_param, :payment_notify => { "payment" => "invalid value" }}, valid_session
        assigns(:payment_notify).should eq(payment_notify)
      end

      it "re-renders the 'edit' template" do
        payment_notify = PaymentNotify.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotify.any_instance.stub(:save).and_return(false)
        put :update, {:id => payment_notify.to_param, :payment_notify => { "payment" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payment_notify" do
      payment_notify = PaymentNotify.create! valid_attributes
      expect {
        delete :destroy, {:id => payment_notify.to_param}, valid_session
      }.to change(PaymentNotify, :count).by(-1)
    end

    it "redirects to the payment_notifies list" do
      payment_notify = PaymentNotify.create! valid_attributes
      delete :destroy, {:id => payment_notify.to_param}, valid_session
      response.should redirect_to(payment_notifies_url)
    end
  end

end
